parameters:
- name: 'ProjectOrSolutionPath'
  type: string
- name: Major
  type: number
  default: 1
- name: Minor
  type: number
  default: 0

stages:
- template: stage-build.yml
  parameters:
    ProjectOrSolutionPath: ${{ parameters.ProjectOrSolutionPath }}
    Major: ${{ parameters.Major }}
    Minor: ${{ parameters.Minor }}
    BuildRelease : false