parameters:
- name: 'ProjectOrSolutionPath'
  type: string
- name: Major
  type: number
  default: 1
- name: Minor
  type: number
  default: 0
- name: BuildRelease
  type: boolean
  default: true

stages:
- stage: build
  jobs:
  - job: build
    pool:
      vmImage: 'windows-latest'
    variables:
      VersionBuild: 0
      VersionRevision: 0
    steps:
      - powershell: |
          $build = ('{0:yy}{1:000}' -f [datetime]::Today, [datetime]::Today.DayOfYear)
          Write-Host "##vso[task.setvariable variable=VersionBuild;]$build"
          $revision = [int](([datetime]::Now - [datetime]::Today).TotalSeconds / 1.4)
          Write-Host "##vso[task.setvariable variable=VersionRevision;]$revision"
          Write-Host 'Build='$build'|Revision='$revision
          Write-Host "##vso[build.updatebuildnumber]${{ parameters.Major }}.${{ parameters.Minor }}.$build.$revision"
        displayName: Calculate Build and Revision part
      - task: DownloadSecureFile@1
        name: privateKey
        displayName: GetPrivateKey
        inputs:
          secureFile: 'be.stateless.snk'
      - task: DotNetCoreCLI@2
        displayName: dotnet restore
        inputs:
          command: 'restore'
          projects: '${{ parameters.ProjectOrSolutionPath }}'
          feedsToUse: 'select'
          vstsFeed: '1b04fa51-ab33-4e2a-9966-fc900bcff434'
          includeNuGetOrg: true
      - task: DotNetCoreCLI@2
        displayName: dotnet build (Debug)
        inputs:
          command: 'build'
          projects: '${{ parameters.ProjectOrSolutionPath }}'
          arguments: '-p:Configuration=Debug;Major=${{ parameters.Major }};Minor=${{ parameters.Minor }};Build=$(VersionBuild);Revision=$(VersionRevision);AssemblyOriginatorKeyFile=$(privateKey.secureFilePath);GeneratePackageOnBuild=false --no-restore'
      - task: DotNetCoreCLI@2
        displayName: dotnet build (Release)
        condition: eq('${{ parameters.BuildRelease }}', true)
        inputs:
          command: 'build'
          projects: '${{ parameters.ProjectOrSolutionPath }}'
          arguments: '-p:Configuration=Release;Major=${{ parameters.Major }};Minor=${{ parameters.Minor }};Build=$(VersionBuild);Revision=$(VersionRevision);AssemblyOriginatorKeyFile=$(privateKey.secureFilePath);GeneratePackageOnBuild=false --no-restore'
      - task: ResharperCli@2
        displayName: ReSharper Code Analysis
        inputs:
          solutionOrProjectPath: '${{ parameters.ProjectOrSolutionPath }}'
          failBuildLevelSelector: 'Warning'
          arguments: '--configuration Release'
          resultsOutputFilePath: '$(Build.SourcesDirectory)/CodeAnalysisReport'