stages:
- stage: publish
  dependsOn: build
  condition: succeeded()
  jobs:
  - job: publish
    steps:
      - task: GitHubRelease@1
        displayName: create release
        inputs:
          gitHubConnection: 'github.com_emmanuelbenitez'
          repositoryName: '$(Build.Repository.Name)'
          action: 'create'
          target: '$(Build.SourceVersion)'
          tagSource: 'gitTag'
          title: '$(Build.BuildNumber)'
          changeLogCompareToRelease: 'lastFullRelease'
          changeLogType: 'commitBased'
      - task: DownloadBuildArtifacts@0
        displayName: download artifact 'packages'
        inputs:
          buildType: 'current'
          downloadType: 'single'
          artifactName: 'packages'
          downloadPath: '$(System.ArtifactsDirectory)'
      - task: DotNetCoreCLI@2
        displayName: nuget push packages
        inputs:
          command: 'push'
          packagesToPush: '$(System.ArtifactsDirectory)/packages/*.*nupkg'
          nuGetFeedType: 'internal'
          publishVstsFeed: '1b04fa51-ab33-4e2a-9966-fc900bcff434'